apiVersion: v1
kind: Service
metadata:
  name: hola-mundo-service
spec:
  selector:
    app: hola-mundo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort  # ideal para Minikube
